from app.models.address import Addresses
from app.models.car_brands import CarBrands
from app.models.car_features import CarFeatures
from app.models.car_media import CarMedia
from app.models.car_models import CarModels
from app.models.car_variants import CarVariants
from app.models.cars import Cars
from app.models.favorites import Favorites
from app.models.inquiries import Inquiries
from app.models.listings import Listings
from app.models.notifications import Notifications
from app.models.ownership_history import OwnershipHistory
from app.models.payments import Payments
from app.models.prediction_features import PredictionFeatures
from app.models.price_predictions import PricePredictions
from app.models.reports import Reports
from app.models.reviews import Reviews
from app.models.service_centers import ServiceCenters
from app.models.service_items import ServiceItems
from app.models.service_records import ServiceRecords
from app.models.transactions import Transactions
from app.models.users import User
