from enum import Enum

class Country(str, Enum):
    US = "United States"
    CA = "Canada"
    GB = "United Kingdom"
    AU = "Australia"
    DE = "Germany"
    FR = "France"
    IN = "India"
    JP = "Japan"
    BR = "Brazil"
    ZA = "South Africa"
    NZ = "New Zealand"
    IT = "Italy"
    ES = "Spain"
    NL = "Netherlands"
    CH = "Switzerland"
    SE = "Sweden"
    NO = "Norway"
    FI = "Finland"
    DK = "Denmark"
    IE = "Ireland"
    MX = "Mexico"
    SG = "Singapore"
    KR = "South Korea"
